data_path: "/content/drive/MyDrive/Colab Notebooks/PhD Test/data/data-learning-control-room-temperature.zip"
sequence: False
horizon: 10
model_alpha: 0.1
random_split: true
split_ratio: 0.7 0.1 0.2

batch_size: 64
model: "fcn"
optimizer: "SGD"
learning_rate: 0.01
scheduler: "ReduceLROnPlateau"
T_max: 10
step_size: 30
gamma: 0.1

num_epochs: 10
device: "cpu"
continue_training: False

trained_weights: ""
save_checkpoint: "/content/drive/MyDrive/Colab Notebooks/PhD Test/checkpoints/all_states.pt"
save_model_checkpoint: "/content/drive/MyDrive/Colab Notebooks/PhD Test/checkpoints/model_weights.pt"
save_matlab_checkpoint: "/content/drive/MyDrive/Colab Notebooks/PhD Test/checkpoints/matlab_weights.mat"